import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#00535b",
        "primary-container": "#006d77",
        "primary-fixed": "#9ff0fb",
        "primary-fixed-dim": "#82d3de",
        secondary: "#236863",
        "secondary-container": "#a9ece5",
        "secondary-fixed": "#acefe7",
        "secondary-fixed-dim": "#90d3cb",
        tertiary: "#713d10",
        "tertiary-container": "#8e5426",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-fixed-dim": "#ffb783",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        surface: "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#006972",
        background: "#f8f9fa",
        outline: "#6f797a",
        "outline-variant": "#bec8ca",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#82d3de",
        "on-primary": "#ffffff",
        "on-primary-container": "#9becf7",
        "on-primary-fixed": "#001f23",
        "on-primary-fixed-variant": "#004f56",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#286d67",
        "on-secondary-fixed": "#00201e",
        "on-secondary-fixed-variant": "#00504b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffd7bd",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-fixed-variant": "#6d390c",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3e494a",
        "on-background": "#191c1d",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
      boxShadow: {
        whisper: "0 8px 24px rgba(25, 28, 29, 0.06)",
        "whisper-up": "0 -8px 24px rgba(0, 0, 0, 0.06)",
        glow: "0 8px 20px rgba(0, 83, 91, 0.25)",
        soft: "0 8px 24px rgba(0, 0, 0, 0.04)",
        elevated: "0 8px 24px rgba(0, 0, 0, 0.12)",
      },
    },
  },
  plugins: [forms],
};

export default config;
