/**
 * Mirrors `frontend/tailwind.config.ts` — single source of truth for product color.
 */
export const colors = {
  primary: "#00535b",
  primaryContainer: "#006d77",
  primaryFixed: "#9ff0fb",
  primaryFixedDim: "#82d3de",
  secondary: "#236863",
  secondaryContainer: "#a9ece5",
  tertiary: "#713d10",
  tertiaryContainer: "#8e5426",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  surface: "#f8f9fa",
  surfaceDim: "#d9dadb",
  surfaceBright: "#f8f9fa",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f3f4f5",
  surfaceContainer: "#edeeef",
  surfaceContainerHigh: "#e7e8e9",
  surfaceContainerHighest: "#e1e3e4",
  surfaceVariant: "#e1e3e4",
  surfaceTint: "#006972",
  background: "#f8f9fa",
  outline: "#6f797a",
  outlineVariant: "#bec8ca",
  inverseSurface: "#2e3132",
  inverseOnSurface: "#f0f1f2",
  inversePrimary: "#82d3de",
  onPrimary: "#ffffff",
  onPrimaryContainer: "#9becf7",
  onSurface: "#191c1d",
  onSurfaceVariant: "#3e494a",
  onBackground: "#191c1d",
  onError: "#ffffff",
  onErrorContainer: "#93000a",
} as const;

export type Colors = typeof colors;
